### ISSUE TITLE
Empty Order Checkout

### ISSUE THREAD

**Issue by reqinamarie** [JLP603/Pizza#11]
**Description:** 
There is no response when checking out an empty order. 

**Steps to reproduce:** 

1. Log in to an account without an order yet
2. Go to order webpage
3. Click "Checkout" button

**Suggestions:**
Either disable the checkout button or display an error message about the empty order.

**Screenshots:**
After clicking the checkout button, the page stays like this:
![image](https://user-images.githubusercontent.com/57651558/104715140-1888e100-5761-11eb-883e-9f900477933a.png)

**Comment by MiguelLeyesa** [comment]
button has been disabled for non logged in users in issue #8 fix

fixed button staying enabled when no items are selected for logged in users
