### ISSUE TITLE
Negative Number in Contact Number

### ISSUE THREAD

**Issue by Plumman** [JLP603/Pizza#13]
Description:
It is possible to put negative number on the contact number

Steps to reproduce:

Log in to a customer account without an order yet
Go to order webpage
Put the order
Click "Checkout" button
Put anything on the Address
Put negative number on the contact number
Suggestions:
Display an error message about the invalid contact number and can not confirm the delivery.

Screenshots:
After clicking the checkout button, It is possible to put negative number:
![image](https://user-images.githubusercontent.com/51822908/104806893-bb029c00-5815-11eb-9082-129e753413b9.png)
The contact number is saved
![image](https://user-images.githubusercontent.com/51822908/104807012-79262580-5816-11eb-9c9d-1ffdd54fcb34.png)

**Comment by MiguelLeyesa** [comment]
added red border warning when inputting negative numbers, 
disabled "Confirm Delivery" Button when contact number if negative
