### ISSUE TITLE
Possible to order as admin

### ISSUE THREAD

**Issue by Plumman** [JLP603/Pizza#14]
Description:
It is possible to order as admin.

Steps to reproduce:

open 2 tabs
enter localhost: 9000 on tab 1
login as customer on tab 1
enter localhost:9000 on tab 2
sign out on tab 2
login as admin on tab 2

go to tab 1
click on order
order something
click on checkout
type information
click on confirm delivery
click on tab 2
reload tab 2
click on tab 1
change pending to completed on tab 1
click on completed customer orders in tab 1
click on pending customer orders in tab 1
click on tab 2
refresh tab 2
change to pending on tab 2
click on tab 1
Suggestions:
Display an error message when ordering as admin and can not confirm the delivery.

Screenshots:
After clicking order on tab 1:
![image](https://user-images.githubusercontent.com/51822908/104807670-94476400-581b-11eb-83fc-09c086c8744d.png)

After clicking checkout:
![image](https://user-images.githubusercontent.com/51822908/104807786-880fd680-581c-11eb-8a14-2c7373a89d48.png)

After confirming delivery:
![image](https://user-images.githubusercontent.com/51822908/104807792-a37ae180-581c-11eb-99eb-5b42aab09cb2.png)

Tab 2 after reloading;
![image](https://user-images.githubusercontent.com/51822908/104807834-f6ed2f80-581c-11eb-9f09-0c0d2a139df2.png)

**Comment by MiguelLeyesa** [comment]
fixed to redirect user type admin to /manager_orders when trying to access user type customer features
