### ISSUE TITLE
Unresponsive order page

### ISSUE THREAD

**Issue by AxelAlba** [JLP603/Pizza#15]
Date: Jan 17, 2021
By: Sandbox
Tested on: Deployed Website
Browser: Google Chrome

Type:
(Coding Error / **Design Issue** / Suggestion)
Severity:
(Fatal / Serious / **Minor**)

**Description**
In the order page, when the website is used in a resolution for a tablet or a phone, the container for choosing the quantity of every item exceeds its parent container.  Additionally, the text "subtotal" exceeds its container with this resolution.

**Screenshot**
![image](https://user-images.githubusercontent.com/54636454/104836862-cc1ddc80-58eb-11eb-8b83-a1d5040fc233.png)

**Steps to Replicate**
1. Open the website
2. From the landing page, go to the order page via the navigation Bar
3. Right click, then click inspect, then change resolution to 768x1024 or iPad.
4. The container for the quantity of every item, as well as the text "subtotal", are not properly aligned to its parent containers.

**Suggestion**
It would be helpful if the user can use the website in any device. Please consider the responsiveness of the order page.

**Comment by MiguelLeyesa** [comment]
added horizontal scrolling for some elements for mobile users for the pages:
/order
/checkout
/user_orders
/manager_orders
