### ISSUE TITLE
No max limit of digits in contact number for checkout page.

### ISSUE THREAD

**Issue by AxelAlba** [JLP603/Pizza#16]
Date: Jan 17, 2021
By: Sandbox
Tested on: Deployed Website
Browser: Google Chrome

Type:
(**Coding Error** / Design Issue / Suggestion)
Severity:
(Fatal / Serious / **Minor**)

**Description**
In the checkout page, when confirming a delivery via the "confirm delivery" button, the form still redirects to the 'user_orders' page even though the input for the contact number is incorrect with it having more than 12 digits, which is the standard number of digits for a mobile number in the Philippines.

**Screenshot**
![image](https://user-images.githubusercontent.com/54636454/104837953-e4ddc080-58f2-11eb-948c-561297d4e07b.png)

**Steps to Replicate**

1. Open the website
2. Login with "test-customer" for username and "root" for password
2. From the landing page, go to the order page via the navigation Bar
3. Order item/s via the order page and press the "checkout" button to redirect to the checkout page.
4. Put any address, and enter a contact number of more than 12 digits
5. Press confirm delivery button

**Suggestion**
Display an error message about the invalid contact number. Additionally, the page will not confirm the delivery and does not redirect to the 'user_orders' page.

**Comment by MiguelLeyesa** [comment]
added a 20 character limit to "Contact No." field to accommodate landlines, mobile numbers, area codes, etc.
