### ISSUE TITLE
No error message in Menu Page

### ISSUE THREAD

**Issue by Skentir** [JLP603/Pizza#7]
**Description**
The website doesn't show any error message when there's no response from the API or if a query returns empty. In my case, there's simply no data to show as there are no errors that appeared in the console log.

**Steps to Replicate**
1. Open the website
2. From the landing page, go to the Menu page via the navigation Bar
3. The Menu page, under the default settings (Category = All), shows an empty page

**Suggestion**
It would be helpful for the user to show an error message in cases that data cannot be loaded or if the query returns an empty result. Best put this in the Menu page rather than a modal or any event-trigger that requires the user to interact with something first before an error message pops up.

**Screenshot**
![Screen Shot 2021-01-14 at 10 00 39 AM](https://user-images.githubusercontent.com/31249788/104534547-73caae80-564f-11eb-94e6-ec5035250f49.png)

**Comment by MiguelLeyesa** [comment]
added "No items" message when a query returns 0 items
