### ISSUE TITLE
Accessibility of Order Page

### ISSUE THREAD

**Issue by Skentir** [JLP603/Pizza#8]
**Description:**
The Order Page is accessible to anonymous users with no account. No message as well if "cart"/orders is empty.

**Steps to reproduce**
1. Open the website  
2. From the landing page, click "Order" in the navigation bar
3. Click "Checkout"

**Suggestion:**
Instead of showing so many warning signs to log in and popping up a message to sign in when checking out, the page should have been inaccessible to anonymous users in the first place. Better yet, disable the checkout button component if it won't do its function or have it redirect to login instead.

A message that my order cart is empty should also be shown, else it may appear to the user that the page is broken.

**Preview:**
![Screen Shot 2021-01-14 at 10 15 55 AM](https://user-images.githubusercontent.com/31249788/104536535-38ca7a00-5653-11eb-9ce0-8ddfcc0472f2.png)

**Comment by MiguelLeyesa** [comment]
The order page is accessible to non logged in users to show that making and placing orders are possible. A new visitor to the site may not know that placing orders is a feature of the website due to not seeing the order tab on the nav bar

fixed button to be disabled when the user is not logged in
