### ISSUE TITLE
Unable to Log-in

### ISSUE THREAD

**Issue by Skentir** [JLP603/Pizza#9]
**Description:**
Upon registration, any attempts in logging with the account credentials I made resulted to "Username not found". This error was not visible since the "Successfully registered!" message is stuck on top of the form.

**Steps to reproduce**
1. Open website
2. Go to Log-in Page and toggle to "Register"
3. Fill-in the fields, by submitting a "Successfully registered!" message should pop up
4. Toggle back to "Log-in"
5. Fill-in the fields again with the same credentials

**Suggestions**
Don't put "I accept terms and conditions" yet in the form field when there's no terms and conditions.
Don't show an error message in the log-in form when the user is not yet done filling up the field. 
Reset the error messages for every after a submission.

**Relevant Preview**
![Screen Shot 2021-01-14 at 10 31 44 AM](https://user-images.githubusercontent.com/31249788/104537892-c6a76480-5655-11eb-9cfa-7da41d3b95a0.png)
Upon changing the success message opacity to 0, the error message was revealed to me:
![Screen Shot 2021-01-14 at 10 39 40 AM](https://user-images.githubusercontent.com/31249788/104537939-dfb01580-5655-11eb-8418-a1e79d9abc27.png)

**Comment by MiguelLeyesa** [comment]
fixed issue where "Successfully registered!" message was blocking error messages
